name: Build production

on:
  push:
    branches:
    - master

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set variables
      run: |
        VER=$(cat VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        registry: "ghcr.io"
    - name: Build and push docker image
      uses: docker/build-push-action@v2
      with:
        file: "Dockerfile"
        context: "."
        push: true
        tags: ghcr.io/ptr-geeks/hts2022:${{env.VERSION}}
